version: 2.1
jobs:
  checkout:
    working_directory: /home/circleci/camsaul/sqlhoney
    docker:
      - image: circleci/clojure:openjdk-17-tools-deps-1.10.3.822-buster
    steps:
      # Checkout source
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      # Fetch deps
      - restore_cache:
          keys:
            - deps-{{ checksum "deps.edn" }}
            - deps-
      - run: clojure -P -M:test
      - run: clojure -P -X:jar
      - run: clojure -P -X:deploy
      - save_cache:
          key: deps-{{ checksum "deps.edn" }}
          paths:
            - /home/circleci/.m2
      # persist so other steps can use it
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .m2
            - camsaul/sqlhoney

  test:
    working_directory: /home/circleci/camsaul/sqlhoney
    docker:
      - image: circleci/clojure:openjdk-17-tools-deps-1.10.3.822-buster
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run tests
          command: clojure -M:test
          no_output_timeout: 5m

  # lint-bikeshed:
  #   working_directory: /home/circleci/camsaul/sqlhoney
  #   docker:
  #     - image: circleci/clojure:lein-2.8.1
  #   steps:
  #     - attach_workspace:
  #         at: /home/circleci
  #     - run:
  #         name: Run Bikeshed linter
  #         command: lein bikeshed
  #         no_output_timeout: 5m

  # lint-eastwood:
  #   working_directory: /home/circleci/camsaul/sqlhoney
  #   docker:
  #     - image: circleci/clojure:lein-2.8.1
  #   steps:
  #     - attach_workspace:
  #         at: /home/circleci
  #     - run:
  #         name: Run Eastwood linter
  #         command: lein eastwood
  #         no_output_timeout: 5m

  # lint-docstrings:
  #   working_directory: /home/circleci/camsaul/sqlhoney
  #   docker:
  #     - image: circleci/clojure:lein-2.8.1
  #   steps:
  #     - attach_workspace:
  #         at: /home/circleci
  #     - run:
  #         name: Run Docstring Checker linter
  #         command: lein docstring-checker
  #         no_output_timeout: 5m

  # lint-namespace-decls:
  #   working_directory: /home/circleci/camsaul/sqlhoney
  #   docker:
  #     - image: circleci/clojure:lein-2.8.1
  #   steps:
  #     - attach_workspace:
  #         at: /home/circleci
  #     - run:
  #         name: Run ns declaration checker
  #         command: lein check-namespace-decls
  #         no_output_timeout: 5m

  deploy:
    working_directory: /home/circleci/camsaul/sqlhoney
    docker:
      - image: circleci/clojure:openjdk-17-tools-deps-1.10.3.822-buster
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Generate pom.xml
          command: clojure -Spom
      - run:
          name: Build JAR
          command: clojure -X:jar
      - run:
          name: Deploy to clojars
          command: clojure -X:deploy

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      # - lint-bikeshed:
      #     requires:
      #       - checkout
      # - lint-eastwood:
      #     requires:
      #       - checkout
      # - lint-docstrings:
      #     requires:
      #       - checkout
      # - lint-namespace-decls:
      #     requires:
      #       - checkout
      - deploy:
          requires:
            - test
            # - lint-bikeshed
            # - lint-eastwood
            # - lint-docstrings
            # - lint-namespace-decls
          filters:
            branches:
              only: master
